name: Build and push

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64, linux/arm/v7, linux/arm/v6
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build_and_push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: test_build
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64, linux/arm/v7, linux/arm/v6
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/bt-mqtt-gateway:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/bt-mqtt-gateway:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
